version: '3.9'

services:
  websocket:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash -c "while sleep 1000; do :; done"
    container_name: websocket
    working_dir: /server
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .:/server:cached

networks:
  app-network:
    driver: bridge
